# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('videos', '0001_initial'), ('videos', '0002_outputvideo_thumbnail'), ('videos', '0003_auto_20140421_1525'), ('videos', '0004_video_thumbnail'), ('videos', '0005_video_raw_job_detalis'), ('videos', '0006_auto_20140422_1132'), ('videos', '0007_remove_video_thumbnail'), ('videos', '0008_video_thumbnails'), ('videos', '0009_auto_20140423_1024'), ('videos', '0010_video_thumbnails'), ('videos', '0011_auto_20160506_1138')]

    initial = True

    dependencies = [
        ('images', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, max_length=2083, null=True)),
                ('unique_hash', models.CharField(max_length=40)),
                ('encoding_id', models.IntegerField(blank=True, null=True)),
                ('encodings_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EncodedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video', to_field='id')),
                ('key', models.CharField(max_length=1024)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('mime_type', models.CharField(max_length=255)),
                ('raw_encoding_details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='md5_hash',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='key',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='video',
            name='unique_hash',
        ),
        migrations.RemoveField(
            model_name='video',
            name='encodings_generated',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='encoding_id',
        ),
        migrations.AddField(
            model_name='video',
            name='raw_job_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='encodedvideo',
            unique_together=set([('video', 'width', 'height', 'mime_type')]),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnails',
            field=models.ManyToManyField(blank=True, to='images.Image'),
        ),
        migrations.AlterField(
            model_name='encodedvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encoded_videos', to='videos.Video'),
        ),
    ]
