# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:07
from __future__ import unicode_literals
from django.db import models, migrations

from django.db import migrations

def copy_to_extra(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    UserExtra = apps.get_model("profiles", "UserExtra")
    fieldnames = [f.get_attname() for f in UserExtra._meta.get_fields()]
    for data in Profile.objects.values(*fieldnames):
        UserExtra.objects.get_or_create(**data)

def copy_from_extra(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    UserExtra = apps.get_model("profiles", "UserExtra")
    for data in UserExtra.objects.values():
        Profile.objects.filter(user_id=data['user_id']).update(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_userextra'),
    ]

    operations = [
        migrations.RunPython(copy_to_extra, copy_from_extra)
    ]
