# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20171103_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_active_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_inactive_email_sent_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='source',
        ),
    ]
