# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educator',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
