# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_user'),
        ('students', '0007_auto_20180126_1127'),
        ('mentors', '0004_auto_20180126_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='approved',
        ),
        migrations.AlterField(
            model_name='userextra',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'student'), (2, 'mentor'), (3, 'educator'), (4, 'parent'), (5, 'family')], default=0),
        ),
    ]
