# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_auto_20180126_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentconnection',
            name='child_profile',
        ),
        migrations.RemoveField(
            model_name='parentconnection',
            name='parent_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_me_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_me_video',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_research_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_research_video',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='child_profiles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Educator',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='ParentConnection',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
