# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-30 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_auto_20180208_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'student'), (3, 'educator'), (5, 'family')], default=0),
        ),
    ]
