# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_login',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_active_on',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_inactive_email_sent_on',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='source',
        ),
    ]
