# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20140421_1526'),
        ('students', '0003_auto_20171106_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
    ]
