# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 01:31
from __future__ import unicode_literals

from django.db import migrations
from profiles.models import UserRole

FIELDNAMES = ['user_id', 'city', 'image_id', 'birthday', 'parent_first_name', 'parent_last_name']

def copy(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    StudentProfile = apps.get_model("students", "StudentProfile")
    for data in Profile.objects.filter(user__extra__role=UserRole.student.value).values(*FIELDNAMES):
        StudentProfile.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20171106_0938'),
        ('profiles', '0037_auto_20171103_0807'),
    ]

    operations = [
        migrations.RunPython(copy)
    ]
