# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20171107_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='full_access',
            field=models.BooleanField(default=False),
        ),
    ]
