# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hellosign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
