# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields
import units.validators


class Migration(migrations.Migration):

    replaces = [('units', '0001_initial'), ('units', '0002_unit_image'), ('units', '0003_resource'), ('units', '0004_remove_unit_challenges'), ('units', '0005_auto_20150123_0602'), ('units', '0006_unit_draft'), ('units', '0007_auto_20150904_1319'), ('units', '0008_auto_20160506_1138'), ('units', '0009_unit_slug'), ('units', '0010_auto_20161007_1400'), ('units', '0011_unit_listed'), ('units', '0012_auto_20161007_1407'), ('units', '0013_remove_unit_draft'), ('units', '0014_auto_20161019_1503')]

    initial = True

    dependencies = [
        ('images', '__first__'),
        ('challenges', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='name of the unit')),
                ('description', models.TextField(blank=True, help_text='blurb for the unit', null=True)),
                ('overview', models.TextField(blank=True, help_text='overview for the unit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standards_alignment_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image', to_field='id')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=128)),
                ('file', s3direct.fields.S3DirectField(blank=True, help_text='Uploads will overwrite files of the same name', null=True)),
                ('units', models.ManyToManyField(blank=True, related_name='resources', to='units.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.Unit', to_field='id')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge', to_field='id')),
                ('display_order', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='challenges',
            field=models.ManyToManyField(blank=True, through='units.UnitChallenge', to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='images.Image'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='standards_alignment_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='images.Image'),
        ),
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, help_text='name that goes in the URL where users access this unit, i.e. /units/{slug}', null=True, validators=[units.validators.validate_has_non_numeric]),
        ),
        migrations.AddField(
            model_name='unit',
            name='listed',
            field=models.BooleanField(default=False, help_text='This unit should be visible in the units listing for all users'),
        ),
    ]
