# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0059_auto_20180315_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Enable this option to show this feedback question to students')),
                ('question', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenges', models.ManyToManyField(blank=True, help_text='This feedback question will show up in these selected DCs', to='challenges.Challenge')),
            ],
            options={
                'verbose_name_plural': 'FeedbackQuestions',
            },
        ),
        migrations.CreateModel(
            name='FeedbackResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
                ('feedback_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
