# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0059_auto_20180315_1519'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Enable this option to show this feedback question to students')),
                ('question_1', models.TextField(blank=True, null=True)),
                ('answer_1_1', models.TextField(blank=True, null=True)),
                ('answer_1_2', models.TextField(blank=True, null=True)),
                ('answer_1_3', models.TextField(blank=True, null=True)),
                ('answer_1_4', models.TextField(blank=True, null=True)),
                ('answer_1_5', models.TextField(blank=True, null=True)),
                ('answer_1_6', models.TextField(blank=True, null=True)),
                ('correct_answer_1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('question_2', models.TextField(blank=True, null=True)),
                ('answer_2_1', models.TextField(blank=True, null=True)),
                ('answer_2_2', models.TextField(blank=True, null=True)),
                ('answer_2_3', models.TextField(blank=True, null=True)),
                ('answer_2_4', models.TextField(blank=True, null=True)),
                ('answer_2_5', models.TextField(blank=True, null=True)),
                ('answer_2_6', models.TextField(blank=True, null=True)),
                ('correct_answer_2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('question_3', models.TextField(blank=True, null=True)),
                ('answer_3_1', models.TextField(blank=True, null=True)),
                ('answer_3_2', models.TextField(blank=True, null=True)),
                ('answer_3_3', models.TextField(blank=True, null=True)),
                ('answer_3_4', models.TextField(blank=True, null=True)),
                ('answer_3_5', models.TextField(blank=True, null=True)),
                ('answer_3_6', models.TextField(blank=True, null=True)),
                ('correct_answer_3', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('question_4', models.TextField(blank=True, null=True)),
                ('answer_4_1', models.TextField(blank=True, null=True)),
                ('answer_4_2', models.TextField(blank=True, null=True)),
                ('answer_4_3', models.TextField(blank=True, null=True)),
                ('answer_4_4', models.TextField(blank=True, null=True)),
                ('answer_4_5', models.TextField(blank=True, null=True)),
                ('answer_4_6', models.TextField(blank=True, null=True)),
                ('correct_answer_4', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('answer_2', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('answer_3', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('answer_4', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
