# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('feedback', '0001_initial'), ('feedback', '0002_auto_20180511_1356'), ('feedback', '0003_auto_20180515_1312')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0059_auto_20180315_1519'),
        ('challenges', '0060_challenge_feedback_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Enable this option to show this feedback question to students')),
                ('question', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback Questions',
            },
        ),
        migrations.CreateModel(
            name='FeedbackResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
                ('feedback_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feedbackresult',
            unique_together=set([('feedback_question', 'challenge', 'user')]),
        ),
        migrations.AlterModelOptions(
            name='feedbackquestion',
            options={},
        ),
    ]
