# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-11 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0060_challenge_feedback_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackresult',
            unique_together=set([('feedback_question', 'challenge', 'user')]),
        ),
    ]
