# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackquestion',
            options={'verbose_name_plural': 'Feedback Questions'},
        ),
    ]
