# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('feedback', '0001_initial'), ('feedback', '0002_auto_20180511_1356'), ('feedback', '0003_auto_20180515_1312')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0001_squashed_0064_remove_progress_mentor'),
        ('feedback', '0001_squashed_0003_auto_20180515_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresult',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='feedbackresult',
            unique_together=set([('feedback_question', 'challenge', 'user')]),
        ),
    ]
