# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200528_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresult',
            name='feedback_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.FeedbackQuestion'),
        ),
    ]
