# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180511_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackquestion',
            options={},
        ),
    ]
