# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180502_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='answer',
        ),
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
