# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0059_auto_20180315_1519'),
        ('feedback', '0003_auto_20180502_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='challenge',
        ),
        migrations.AddField(
            model_name='feedback',
            name='challenges',
            field=models.ManyToManyField(blank=True, help_text='This feedback question will show up in these selected DCs', to='challenges.Challenge'),
        ),
    ]
