version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/python:3.6.5-stretch-node-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          REDIS_TEST_URL: redis://localhost:6379/1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      - image: circleci/redis:4.0.9
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - restore_cache:
          keys:
            - pip-packages-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: pip-packages-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

      - restore_cache:
          keys:
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          command: npm install
      - save_cache:
          key: node-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "/usr/local/lib/node_modules"

      - run: mkdir test-reports
      - run: pipenv run python manage.py collectstatic --noinput
      - run:
          name: Pytest
          command: pipenv run pytest -s -v 2>&1 | tee test-reports/pytest.log
      - run:
          name: Jest
          command: npx jest --ci 2>&1 | tee test-reports/jest.log

      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

      - deploy:
          name: Deploy to staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/curiositystaging.git develop:master
            fi