version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/python:3.6.5-stretch-node-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          REDIS_TEST_URL: redis://localhost:6379/1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      - image: circleci/redis:4.0.9
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run: npm ci
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run: mkdir test-reports
      - run:
          name: Pytest
          command: pipenv run pytest --junitxml=test-reports/pytest-results.xml
      - run:
          name: Jest
          command: npx jest --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "test-reports/jest-results.xml"

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - deploy:
          name: Deploy to staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/curiositystaging.git develop:master
            fi