# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-01 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seasonmarker',
            unique_together=set([('start', 'end', 'name')]),
        ),
    ]
