# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0021_auto_20171207_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='slug',
            field=models.SlugField(blank=True, help_text='If provided, users can sign up for this membership at the slug url', null=True, unique=True),
        ),
    ]
