# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 20:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0024_auto_20180131_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='slug',
            field=models.SlugField(blank=True, help_text='If provided, users can sign up for this membership at the slug url', null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
