# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='child_profiles',
            field=models.ManyToManyField(blank=True, related_name='parent_profiles', through='parents.ParentConnection', to='students.StudentProfile'),
        ),
    ]
