# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 01:40
from __future__ import unicode_literals

from django.db import migrations
from profiles.models import UserRole

FIELDNAMES = ['user_id', 'city', 'image_id']

def copy(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    ParentProfile = apps.get_model("parents", "ParentProfile")
    for data in Profile.objects.filter(user__extra__role=UserRole.parent.value).values(*FIELDNAMES):
        ParentProfile.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_auto_20171107_1133'),
        ('profiles', '0037_auto_20171103_0807'),
    ]

    operations = [
        migrations.RunPython(copy)
    ]
