# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 19:31
from __future__ import unicode_literals

from django.db import migrations

def copy(apps, schema_editor):
    OldParentConnection = apps.get_model("profiles", "ParentConnection")
    ParentConnection = apps.get_model("parents", "ParentConnection")
    fieldnames = [f.get_attname() for f in ParentConnection._meta.get_fields()]
    fieldnames.remove('id')
    for data in OldParentConnection.objects.values(*fieldnames):
        ParentConnection.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_auto_20171107_1740'),
    ]

    operations = [
        migrations.RunPython(copy)
    ]
