# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_auto_20171129_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentconnection',
            name='child_profile',
        ),
        migrations.RemoveField(
            model_name='parentconnection',
            name='parent_profile',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='child_profiles',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ParentConnection',
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
    ]
