# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 21:48
from __future__ import unicode_literals

from django.db import migrations
from profiles.models import UserRole


def delete_parent_accounts(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(extra__role=UserRole['parent'].value).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_auto_20190117_1340'),
    ]

    operations = [
        migrations.RunPython(delete_parent_accounts)
    ]
