# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmcomments', '0001_squashed_0016_remove_comment_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='question_text',
            field=models.TextField(help_text='If the comment is in direct reply to a question, this will contain the full text of the question.'),
        ),
    ]
