# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('md5_hash', models.CharField(blank=True, max_length=32)),
                ('key', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
