# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('documents', '0001_initial'), ('documents', '0002_document_filename')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('md5_hash', models.CharField(blank=True, max_length=32)),
                ('key', models.CharField(blank=True, max_length=1024)),
                ('filename', models.CharField(blank=True, max_length=2048)),
            ],
        ),
    ]
