# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0003_auto_20140421_1526'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0011_auto_20160506_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('employer', models.TextField(blank=True)),
                ('expertise', models.TextField(blank=True)),
                ('about_me', models.TextField(blank=True)),
                ('about_research', models.TextField(blank=True)),
                ('about_me_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.Image')),
                ('about_me_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.Video')),
                ('about_research_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.Image')),
                ('about_research_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.Video')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
