# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 21:56
from __future__ import unicode_literals

from django.db import migrations
from profiles.models import UserRole

FIELDNAMES = [
    'user_id',
    'city',
    'image_id',
    'title',
    'employer',
    'expertise',
    'about_me',
    'about_research',
    'about_me_image_id',
    'about_me_video_id',
    'about_research_image_id',
    'about_research_video_id'
]

def copy(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    MentorProfile = apps.get_model("mentors", "MentorProfile")
    for data in Profile.objects.filter(user__extra__role=UserRole.mentor.value).values(*FIELDNAMES):
        MentorProfile.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy)
    ]
