# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 19:47
from __future__ import unicode_literals

from django.db import migrations, connection

def copy(apps, schema_editor):
    # F() query can't handle joins, so drop to raw SQL I guess
    with connection.cursor() as cursor:
        cursor.execute('''
            UPDATE mentors_mentorprofile
            SET full_access = approved
            FROM profiles_userextra
            WHERE mentors_mentorprofile.user_id = profiles_userextra.user_id;
        ''')

class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentorprofile_full_access'),
    ]

    operations = [
        migrations.RunPython(copy, migrations.RunPython.noop)
    ]
