# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 19:24
from __future__ import unicode_literals

import curiositymachine.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('educators', '0001_initial'), ('educators', '0002_auto_20171108_1408'), ('educators', '0003_impactsurvey'), ('educators', '0004_auto_20171109_0701'), ('educators', '0005_educatorprofile_location'), ('educators', '0006_educatorprofile_title_i'), ('educators', '0007_auto_20180503_1143'), ('educators', '0008_auto_20180508_1723'), ('educators', '0009_auto_20190131_1250')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('profiles', '0037_auto_20171103_0807'),
        ('images', '0003_auto_20140421_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True, validators=[curiositymachine.validators.validate_simple_latin])),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educatorprofile', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.Location')),
                ('title_i', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpactSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveIntegerField(blank=True, null=True)),
                ('teacher_count', models.PositiveIntegerField(blank=True, null=True)),
                ('challenge_count', models.PositiveIntegerField(blank=True, null=True)),
                ('in_classroom', models.BooleanField(default=False)),
                ('out_of_classroom', models.BooleanField(default=False)),
                ('hours_per_challenge', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
