# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 22:08
from __future__ import unicode_literals

from django.db import migrations
from profiles.models import UserRole

FIELDNAMES = ['user_id', 'city', 'image_id', 'organization']

def copy(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    EducatorProfile = apps.get_model("educators", "EducatorProfile")
    for data in Profile.objects.filter(user__extra__role=UserRole.educator.value).values(*FIELDNAMES):
        EducatorProfile.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy)
    ]
