# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educators', '0002_auto_20171108_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveIntegerField(blank=True, default=0)),
                ('teacher_count', models.PositiveIntegerField(blank=True, default=0)),
                ('challenge_count', models.PositiveIntegerField(blank=True, default=0)),
                ('in_classroom', models.BooleanField(default=False)),
                ('out_of_classroom', models.BooleanField(default=False)),
                ('hours_per_challenge', models.PositiveIntegerField(blank=True, default=0)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
