# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 15:01
from __future__ import unicode_literals

from django.db import migrations

def copy(apps, schema_editor):
    ProfileImpactSurvey = apps.get_model("profiles", "ImpactSurvey")
    ImpactSurvey = apps.get_model("educators", "ImpactSurvey")
    fieldnames = [f.get_attname() for f in ImpactSurvey._meta.get_fields()]
    fieldnames.remove('id')
    for data in ProfileImpactSurvey.objects.values(*fieldnames):
        ImpactSurvey.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0003_impactsurvey'),
    ]

    operations = [
        migrations.RunPython(copy)
    ]
