# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('educators', '0004_auto_20171109_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatorprofile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.Location'),
        ),
    ]
