# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0005_educatorprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatorprofile',
            name='title_i',
            field=models.BooleanField(default=False),
        ),
    ]
