# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 18:43
from __future__ import unicode_literals

import curiositymachine.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0006_educatorprofile_title_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[curiositymachine.validators.validate_simple_latin]),
        ),
    ]
