# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0007_auto_20180503_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactsurvey',
            name='challenge_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impactsurvey',
            name='hours_per_challenge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impactsurvey',
            name='student_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impactsurvey',
            name='teacher_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
