# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 21:27
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_familyprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='18005555555', max_length=128),
            preserve_default=False,
        ),
    ]
