# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import families.models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_auto_20180201_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family_role',
            field=models.SmallIntegerField(choices=[(None, 'Select role...'), (0, families.models.FamilyRole.display), (1, families.models.FamilyRole.display)]),
        ),
    ]
