# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-06 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import families.models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_auto_20180208_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family_role',
            field=models.SmallIntegerField(choices=[(None, 'Select role...'), (0, families.models.FamilyRole.display), (1, families.models.FamilyRole.display)]),
        ),
    ]
