# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0009_auto_20180315_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family_role',
            field=models.SmallIntegerField(choices=[(None, 'Select role...'), (0, 'Parent or guardian'), (1, 'Child')]),
        ),
    ]
