# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 22:28
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0010_auto_20180503_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
