# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0012_familyprofile_awardforce_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='members_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
