# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0013_familyprofile_members_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='consent',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
