# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-31 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0013_familyprofile_members_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='awardforce_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
