# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-31 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0014_familyprofile_awardforce_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardForceIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='familyprofile',
            name='awardforce_email',
        ),
        migrations.RemoveField(
            model_name='familyprofile',
            name='awardforce_slug',
        ),
    ]
