# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-02 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0015_auto_20181031_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='birthday',
        ),
    ]
