# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0016_remove_familymember_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardforceintegration',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
