# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0019_auto_20181129_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyprofile',
            name='phone',
        ),
    ]
