# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_squashed_0064_remove_progress_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='challenge',
            field=models.ForeignKey(help_text='The challenge that this resource should be associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.Challenge'),
        ),
    ]
