# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0052_auto_20161019_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='students',
            new_name='doers',
        ),
        migrations.AddField(
            model_name='progress',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_progresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
