# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:04
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def copy(apps, schema_editor):
    Progress = apps.get_model("challenges", "Progress")
    Progress.objects.all().update(owner=F('student'))

class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0053_auto_20171214_1204'),
    ]

    operations = [
        migrations.RunPython(copy)
    ]
