# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0054_auto_20171214_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='student',
        ),
    ]
