# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0055_remove_progress_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
