# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0056_auto_20180116_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='free',
            field=models.BooleanField(default=True, help_text='Free challenges are available to users regardless of membership'),
        ),
    ]
