# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0058_auto_20180222_1334'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set([('challenge', 'owner')]),
        ),
    ]
