# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('challenges', '0059_auto_20180315_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='feedback_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.FeedbackQuestion'),
        ),
    ]
