# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0060_challenge_feedback_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='build_subheader',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='plan_call_to_action',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='plan_subheader',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='reflect_subheader',
        ),
    ]
