# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0061_auto_20180612_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='core',
        ),
    ]
