# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0062_remove_challenge_core'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='mentor_guide',
        ),
    ]
