# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0063_remove_challenge_mentor_guide'),
        ('cmcomments', '0015_auto_20170814_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='mentor',
        ),
    ]
