# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 18:43
from __future__ import unicode_literals

import curiositymachine.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180130_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.TextField(validators=[curiositymachine.validators.validate_simple_latin]),
        ),
    ]
