# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('lessons', '0001_initial'), ('lessons', '0002_auto_20180611_0843'), ('lessons', '0003_comment'), ('lessons', '0004_auto_20180612_0851'), ('lessons', '0005_lesson_title'), ('lessons', '0006_auto_20180615_1033'), ('lessons', '0007_auto_20180618_0832'), ('lessons', '0008_auto_20180618_0845'), ('lessons', '0009_lesson_start'), ('lessons', '0010_quiz_quizresult'), ('lessons', '0011_lesson_quiz'), ('lessons', '0012_auto_20180713_1321'), ('lessons', '0013_auto_20180716_1219'), ('lessons', '0014_auto_20180719_0714'), ('lessons', '0015_auto_20180823_1217'), ('lessons', '0016_lesson_draft'), ('lessons', '0017_auto_20190314_0901-1')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('images', '0003_auto_20140421_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspiration', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('build', models.TextField(blank=True)),
                ('further', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'progresses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set([('lesson', 'owner')]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL)),
                ('lesson_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Progress')),
                ('upload_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('upload_id', models.PositiveIntegerField(blank=True, null=True)),
                ('role', models.CharField(default='comment', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text='Image shown on the dashboard', null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Description shown on the dashboard', null=True),
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='start',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.TextField()),
                ('answer_1_1', models.TextField()),
                ('answer_1_2', models.TextField()),
                ('answer_1_3', models.TextField()),
                ('correct_answer_1', models.PositiveSmallIntegerField()),
                ('explanation_1', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Quiz')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Quiz'),
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='upload_prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='explanation_1',
            field=models.TextField(help_text='HTML allowed'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
