# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20140421_1526'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0002_auto_20180611_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image')),
                ('lesson_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Progress')),
            ],
        ),
    ]
