# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20180612_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
