# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20140421_1526'),
        ('lessons', '0006_auto_20180615_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text='Image shown on the dashboard', null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Description shown on the dashboard', null=True),
        ),
    ]
