# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_quiz_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Quiz'),
        ),
    ]
