# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20180713_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='text_prompt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='upload_prompt',
            field=models.TextField(default=''),
        ),
    ]
