# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_auto_20180716_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='text_prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='upload_prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
