# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_auto_20180719_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='explanation_1',
            field=models.TextField(help_text='HTML allowed'),
        ),
    ]
