# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_auto_20180823_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='build',
            field=models.CharField(default='not-started', max_length=20),
        ),
        migrations.AddField(
            model_name='progress',
            name='further',
            field=models.CharField(default='not-started', max_length=20),
        ),
        migrations.AddField(
            model_name='progress',
            name='inspiration',
            field=models.CharField(default='not-started', max_length=20),
        ),
        migrations.AddField(
            model_name='progress',
            name='plan',
            field=models.CharField(default='not-started', max_length=20),
        ),
        migrations.AddField(
            model_name='progress',
            name='reflect',
            field=models.CharField(default='not-started', max_length=20),
        ),
        migrations.AddField(
            model_name='progress',
            name='start',
            field=models.CharField(default='not-started', max_length=20),
        ),
    ]
