# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-28 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_auto_20180823_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
