# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_lesson_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='publish',
        ),
        migrations.AddField(
            model_name='lesson',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
