# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-14 14:49
from __future__ import unicode_literals

from django.db import migrations

def set_draft(apps, schema_editor):
    Lesson = apps.get_model('lessons', 'Lesson')
    for lesson in Lesson.objects.all():
        lesson.draft = False
        lesson.save(update_fields=['draft'])

class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_lesson_draft'),
    ]

    operations = [
        migrations.RunPython(set_draft, elidable=True),
    ]
